### ISSUE TITLE
Testing the presence of the optional argument feature_weights in the solver

### ISSUE THREAD

**Issue by aldro61** [aldro61/pyscm#29]
We used if(feature_weights). For some reason, this fails on some platforms and leads to a segfault. It works on mac. Temporary fix will be to pass np.zeros(X.shape[1]) as feature_weights.

**Comment by aldro61** [comment]
If anyone wants to investigate this, feel free to self-assign.

**Comment by plpla** [comment]
The problem comes from `npy_intp feature_weights_dim0 = PyArray_DIM(feature_weights, 0);`
This function must receive a PyArrayObject* but receives NULL when the feature_weights argument is not used, causing a SegFault (problem in the Array API?).
I propose to change the problematic section to:
`npy_intp feature_weights_dim0 = 0;
    if(feature_weights){
        feature_weights_dim0 = PyArray_DIM(feature_weights, 0);
    }`
It is tested and it seems to work.
What do you think?

**Comment by plpla** [comment]
From numpy source, the function `PyArray_DIM` tries to access an attribute that is non-existent.
See https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/ndarraytypes.h#L1476

**Comment by aldro61** [comment]
I thought I had included the if, like for all other operations on this argument. Good catch! Please create a patch and make a pull request. Also update the scm.py file to remove the np.ones feature weights.
